# Check for Updates
--update

# Concurrent download parts
-N 4

# Output path
-P ./downloads/

# Output template (all files in folder with vid title)
-o "%(title)s/%(title)s [%(id)s].%(ext)s"

# Save thumbnail
--write-thumbnail

# Save link to video
--write-link

# Write subtitles
--write-subs

# Mark SponsorBlock sections
--sponsorblock-mark all